// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ytG1JqRo6nkgE1UgDUNVKuH5f7feYQw',
    appId: '1:558955224418:web:4d68c36887c20bd21ea03b',
    messagingSenderId: '558955224418',
    projectId: 'test-db-5ff6b',
    authDomain: 'test-db-5ff6b.firebaseapp.com',
    storageBucket: 'test-db-5ff6b.appspot.com',
    measurementId: 'G-4WFDXHYPHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK-stXVm2rNHzc7hXhlZcGDJ0JDzuhJ4o',
    appId: '1:558955224418:android:7e48a917fe92bb861ea03b',
    messagingSenderId: '558955224418',
    projectId: 'test-db-5ff6b',
    storageBucket: 'test-db-5ff6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3xBqCod90YY-P8gK1O_tu1Abz2-lOKV4',
    appId: '1:558955224418:ios:43fdb8195fb6eb101ea03b',
    messagingSenderId: '558955224418',
    projectId: 'test-db-5ff6b',
    storageBucket: 'test-db-5ff6b.appspot.com',
    iosClientId: '558955224418-ns1a1ec11npo71qe5jrcp2dbldv7qsnj.apps.googleusercontent.com',
    iosBundleId: 'com.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3xBqCod90YY-P8gK1O_tu1Abz2-lOKV4',
    appId: '1:558955224418:ios:43fdb8195fb6eb101ea03b',
    messagingSenderId: '558955224418',
    projectId: 'test-db-5ff6b',
    storageBucket: 'test-db-5ff6b.appspot.com',
    iosClientId: '558955224418-ns1a1ec11npo71qe5jrcp2dbldv7qsnj.apps.googleusercontent.com',
    iosBundleId: 'com.example',
  );
}
